### ISSUE TITLE
404 links in front page

### ISSUE THREAD

**Issue by etheory** [oneapi-src/oneMKL#637]
# Summary
There are 404 links on the front page of this repository

# URLs
Developer Reference
[oneMath Defined Datatypes](https://uxlfoundation.github.io/oneMath/onemath-datatypes.html) - results in 404
[Dense Linear Algebra](https://uxlfoundation.github.io/oneMath/domains/dense_linear_algebra.html) - results in 404

# Additional details
Please either remove or fix these links.

**Comment by vmalia** [comment]
Looks like an update to the documentation broke the links in the repository, thanks for reporting!

**Comment by itopinsk** [comment]
@etheory the links in [Documentation section](https://github.com/uxlfoundation/oneMath?tab=readme-ov-file#documentation) were fixed. Please let us know if any issue exists.

**Comment by etheory** [comment]
You've just removed these links, not actually fixed them. There is now a **sparse linear algebra** but no **dense linear algebra** link, and the **oneMath Defined Datatypes** link is gone also.

Are you able to fix them rather then remove them? Thanks.

**Comment by itopinsk** [comment]
The reason is that the mentioned links were referring to duplicated pages and the information provided initially via those links has been kept in [oneMath specification](https://oneapi-spec.uxlfoundation.org/specifications/oneapi/latest/elements/onemath/source/):
[API Design](https://oneapi-spec.uxlfoundation.org/specifications/oneapi/latest/elements/onemath/source/architecture/architecture#api-design)
[Dense Linear Algebra](https://oneapi-spec.uxlfoundation.org/specifications/oneapi/latest/elements/onemath/source/domains/domains#dense-linear-algebra)

**Comment by etheory** [comment]
> The reason is that the mentioned links were referring to duplicated pages and the information provided initially via those links has been kept in [oneMath specification](https://oneapi-spec.uxlfoundation.org/specifications/oneapi/latest/elements/onemath/source/): [API Design](https://oneapi-spec.uxlfoundation.org/specifications/oneapi/latest/elements/onemath/source/architecture/architecture#api-design) [Dense Linear Algebra](https://oneapi-spec.uxlfoundation.org/specifications/oneapi/latest/elements/onemath/source/domains/domains#dense-linear-algebra)

Thank you kindly @itopinsk - that clarifies nicely. Closing the ticket as it's now done, thanks.
